version: '3.3'

services:

  books-scraper:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: books-scraper

    image: gutogm/books-scraper:latest
    volumes:
      - ./:/application
    network_mode: "host"
    environment:
      API_URL: ${API_URL:-http://localhost:3000}
    working_dir: /application
    command: npm run app